name: WebUI Action

on:
    workflow_dispatch:
        inputs:
            productpath:
                description: 'Product Path'
                required: false
            projectdir:
                description: 'Project Directory'
                required: false
            suite:
                description: 'Test Suite Name'
                required: true
            logformat:
                description: 'Test Suite Name'
                required: true

jobs:

    WebUI-Action:
        runs-on: self-hosted
        name: Execute WebUI Test
        steps:
         - name: Execute Test
           uses: SonaHJ/TraditionalUIAction@main
           with:
            productpath: '${{ github.event.inputs.productpath }}'
            projectdir: '${{ github.event.inputs.projectdir }}'
            suite: '${{ github.event.inputs.suite }}'
            logformat: '${{ github.event.inputs.logformat }}'
